import { useEffect, useState } from 'react';
const lucidPoster='/resources/lucid-cover-small.jpg';
const kaegoProfile='/resources/kaego-profile-small.jpg';
const cuttingPoster='/resources/cutting-poster.png';
const musicStill='/resources/burned-coffee-cover.jpg';
const silentStill='/resources/Screenshot 2026-09-26 at 13.25.33.png';
const burnedCoffeeFilm='/resources/burned-coffee-final.mp4';
const albratrumFilm='/resources/albratrum-film.mp4';
function App(){
 const [route,setRoute]=useState(window.location.hash||'#/');
 useEffect(()=>{const sync=()=>{setRoute(window.location.hash||'#/');window.scrollTo(0,0)};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 const path=route.replace('#','')||'/';
 const Nav=({light=false}:{light?:boolean})=><header className={'nav '+(light?'nav-light':'')}><a className="brand" href="#/">KAE <span>STUDIOS</span></a><nav><a href="#/portfolio">Portfolio</a><a href="#/about">About</a><a href="#/contact">Contact</a></nav></header>;
 const Footer=()=> <footer><span>KAE STUDIOS © 2026</span><span>FILM PRODUCTION · LONDON</span></footer>;
 const Back=()=> <button className="back-arrow" onClick={()=>window.history.length>1?window.history.back():window.location.hash='#/'} aria-label="Go back">←</button>;
 if(path==='/portfolio')return <div className="page paper"><Nav light/><Back/><main className="portfolio"><div className="page-head"><p>SELECTED WORK</p></div>
  <a className="work-card" href="#/film/lucid"><div className="work-art" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.55)),url('${lucidPoster}')`}}><span>2024 / SHORT FILM</span><strong>LUCID</strong><i>View project ↗</i></div><div className="work-meta"><h2>Lucid</h2><p>Short film</p></div></a>
  <a className="work-card" href="#/film/cutting"><div className="work-art" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.5)),url('${cuttingPoster}')`}}><span>2024 / DOCUMENTARY</span><strong>CUTTING<br/>THROUGH LABELS</strong><i>View project ↗</i></div><div className="work-meta"><h2>Cutting Through Labels</h2><p>Documentary</p></div></a>
  <a className="work-card" href="#/film/burned-coffee"><div className="work-art" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.5)),url('${musicStill}')`}}><span>2022 / MUSIC VIDEO</span><i>View project ↗</i></div><div className="work-meta"><h2>Burned Coffee</h2><p>Music video</p></div></a>
  <a className="work-card" href="#/film/albratrum"><div className="work-art" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.5)),url('${silentStill}')`}}><span>2022 / SILENT FILM</span><strong>/ALBRATRUM/</strong><i>View project ↗</i></div><div className="work-meta"><h2>/albratrum/</h2><p>Silent film</p></div></a>
  <a className="work-card" href="https://www.youtube.com/watch?v=p6sHiB6lRbw" target="_blank" rel="noreferrer"><div className="work-art" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.45)),url('https://img.youtube.com/vi/p6sHiB6lRbw/maxresdefault.jpg')`}}><span>2019 / EVENT VIDEOGRAPHY</span><strong>EVENT<br/>VIDEOGRAPHY</strong><i>Watch on YouTube ↗</i></div><div className="work-meta"><h2>Event Videography</h2><p>Camera work</p></div></a>
 </main><Footer/></div>;
 const simpleProject=(title:string,type:string,image:string,body:React.ReactNode)=><div className="page paper"><Nav light/><Back/><main className="case-study"><div className="case-kicker"><a href="#/portfolio">← Portfolio</a><span>{type}</span></div><h1>{title}</h1><div className="case-hero" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(0,0,0,.5)),url('${image}')`}}><strong>{title.toUpperCase()}</strong></div>{body}</main><Footer/></div>;
 if(path==='/film/lucid')return simpleProject('Lucid','SHORT FILM',lucidPoster,<div className="project-action"><a href="https://vimeo.com/993079594" target="_blank" rel="noreferrer">View film on Vimeo ↗</a></div>);
 if(path==='/film/cutting')return simpleProject('Cutting Through Labels','DOCUMENTARY',cuttingPoster,<div className="project-action"><a href="https://vimeo.com/1108093726" target="_blank" rel="noreferrer">View film on Vimeo ↗</a></div>);
 if(path==='/film/burned-coffee')return simpleProject('','MUSIC VIDEO',musicStill,<div className="project-action"><p>Produced by Kaego Paul</p><div className="watch-film"><h2>Watch film</h2><video controls playsInline preload="metadata" poster={musicStill}><source src={burnedCoffeeFilm} type="video/mp4"/></video></div></div>);
 if(path==='/film/albratrum')return simpleProject('','SILENT FILM',silentStill,<div className="project-action"><p>Shot and produced by Kaego Paul</p><div className="watch-film"><h2>Watch film</h2><video controls playsInline preload="metadata" poster={silentStill}><source src={albratrumFilm} type="video/mp4"/></video></div></div>);
 if(path==='/about')return <div className="page paper"><Nav light/><Back/><main className="about-page"><div className="page-head"><p>ABOUT / PRODUCER & FILMMAKER</p><h1>Kaego Paul</h1></div><div className="about-grid"><div className="kae-frame"><img src={kaegoProfile} alt="Kaego Paul"/></div><div className="about-copy" style={{textAlign:"center",display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",alignSelf:"stretch"}}><p className="lead">Kaego Paul is a creative producer with a BA (Hons) in Film Production and experience in event videography, broadcasting and short films.</p><p><a href="https://www.imdb.com/name/nm16183596/" target="_blank" rel="noreferrer">IMDb ↗</a></p></div></div></main><Footer/></div>;
 if(path==='/contact')return <div className="page contact-page"><Nav/><Back/><main><a href="mailto:link@kaestudios.co.uk">link@kaestudios.co.uk</a></main><Footer/></div>;
 return <div className="site"><Nav/><main><section className="hero"><div className="hero-bg"><div className="light"/><div className="grain"/></div><div className="hero-top"><span></span><span>LONDON</span></div><div className="hero-title"><h1>KAE</h1><h1 className="outline">STUDIOS</h1></div><div className="hero-bottom"><p>FILM / DOCUMENTARY / VISUAL STORYTELLING</p><a href="#/portfolio">VIEW PORTFOLIO →</a></div></section></main><Footer/></div>;
}
export default App;